spring.application.name=ProyectoDesarrolloColectivo
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/DBDesarrollocolectivo_in5cm?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Guatemala&characterEncoding=utf8
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Solo en desarrollo mientras sincronizas tablas
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

spring.sql.init.mode=never
spring.jackson.time-zone=America/Guatemala
spring.jackson.date-format=yyyy-MM-dd

logging.level.org.springframework.orm.jpa=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE